








 

<%@ page language="java" errorPage="/error.jsp" pageEncoding="UTF-8" contentType="text/html;charset=utf-8" %>
<%@ include file="/Templates/taglibs.jsp"%>
<%@page import="com.ko.webapp.util.FormHandler,com.ko.webapp.util.PageUtil"%>
<%
	FormHandler formHandler = new FormHandler(request);
	PageUtil pageUtil = new PageUtil(request);
%>
<a href="<c:url value="/process2?action=ApplicationArrestLawbreaker&cmd=list"/>">Back</a>
<table><tr><td><font color="red"><%=formHandler.getFormMessage()%></font></td></tr></table>
<table border="1">
	<tr>
		<td>ID</td>
		<td>${applicationArrestLawbreaker.id}</td>
	</tr>
	<tr>
			<td>ismistake_desc</td>
		<td>
					${applicationArrestLawbreaker.ismistake_desc}
				</td>
		</tr>
	<tr>
			<td>ismistake</td>
		<td>
					${applicationArrestLawbreaker.ismistake}
				</td>
		</tr>
	<tr>
			<td>paper_no</td>
		<td>
					${applicationArrestLawbreaker.paper_no}
				</td>
		</tr>
	<tr>
			<td>company_name</td>
		<td>
					${applicationArrestLawbreaker.company_name}
				</td>
		</tr>
	<tr>
			<td>company_title_code</td>
		<td>
					${applicationArrestLawbreaker.company_title_code}
				</td>
		</tr>
	<tr>
			<td>corporation_code</td>
		<td>
					${applicationArrestLawbreaker.corporation_code}
				</td>
		</tr>
	<tr>
			<td>excise_reg_no</td>
		<td>
					${applicationArrestLawbreaker.excise_reg_no}
				</td>
		</tr>
	<tr>
			<td>other_name</td>
		<td>
					${applicationArrestLawbreaker.other_name}
				</td>
		</tr>
	<tr>
			<td>birth_date</td>
		<td>
					<fmt:formatDate value="${applicationArrestLawbreaker.birth_date}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>sex</td>
		<td>
					${applicationArrestLawbreaker.sex}
				</td>
		</tr>
	<tr>
			<td>title_code</td>
		<td>
					${applicationArrestLawbreaker.title_code}
				</td>
		</tr>
	<tr>
			<td>update_on</td>
		<td>
					<fmt:formatDate value="${applicationArrestLawbreaker.update_on}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>update_by</td>
		<td>
					${applicationArrestLawbreaker.update_by}
				</td>
		</tr>
	<tr>
			<td>create_on</td>
		<td>
					<fmt:formatDate value="${applicationArrestLawbreaker.create_on}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>create_by</td>
		<td>
					${applicationArrestLawbreaker.create_by}
				</td>
		</tr>
	<tr>
			<td>cancel_by</td>
		<td>
					${applicationArrestLawbreaker.cancel_by}
				</td>
		</tr>
	<tr>
			<td>cancel_date</td>
		<td>
					<fmt:formatDate value="${applicationArrestLawbreaker.cancel_date}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>iscancel</td>
		<td>
					${applicationArrestLawbreaker.iscancel}
				</td>
		</tr>
	<tr>
			<td>inv_no</td>
		<td>
					${applicationArrestLawbreaker.inv_no}
				</td>
		</tr>
	<tr>
			<td>book_no</td>
		<td>
					${applicationArrestLawbreaker.book_no}
				</td>
		</tr>
	<tr>
			<td>fine</td>
		<td>
					${applicationArrestLawbreaker.fine}
				</td>
		</tr>
	<tr>
			<td>invcode</td>
		<td>
					${applicationArrestLawbreaker.invcode}
				</td>
		</tr>
	<tr>
			<td>paid_time_off</td>
		<td>
					${applicationArrestLawbreaker.paid_time_off}
				</td>
		</tr>
	<tr>
			<td>mother_name</td>
		<td>
					${applicationArrestLawbreaker.mother_name}
				</td>
		</tr>
	<tr>
			<td>father_name</td>
		<td>
					${applicationArrestLawbreaker.father_name}
				</td>
		</tr>
	<tr>
			<td>age</td>
		<td>
					${applicationArrestLawbreaker.age}
				</td>
		</tr>
	<tr>
			<td>career</td>
		<td>
					${applicationArrestLawbreaker.career}
				</td>
		</tr>
	<tr>
			<td>race_id</td>
		<td>
					${applicationArrestLawbreaker.race_id}
				</td>
		</tr>
	<tr>
			<td>nationality_id</td>
		<td>
					${applicationArrestLawbreaker.nationality_id}
				</td>
		</tr>
	<tr>
			<td>province</td>
		<td>
					${applicationArrestLawbreaker.province}
				</td>
		</tr>
	<tr>
			<td>district</td>
		<td>
					${applicationArrestLawbreaker.district}
				</td>
		</tr>
	<tr>
			<td>subdistrict</td>
		<td>
					${applicationArrestLawbreaker.subdistrict}
				</td>
		</tr>
	<tr>
			<td>moo</td>
		<td>
					${applicationArrestLawbreaker.moo}
				</td>
		</tr>
	<tr>
			<td>road</td>
		<td>
					${applicationArrestLawbreaker.road}
				</td>
		</tr>
	<tr>
			<td>soi</td>
		<td>
					${applicationArrestLawbreaker.soi}
				</td>
		</tr>
	<tr>
			<td>address_no</td>
		<td>
					${applicationArrestLawbreaker.address_no}
				</td>
		</tr>
	<tr>
			<td>last_name</td>
		<td>
					${applicationArrestLawbreaker.last_name}
				</td>
		</tr>
	<tr>
			<td>middle_name</td>
		<td>
					${applicationArrestLawbreaker.middle_name}
				</td>
		</tr>
	<tr>
			<td>first_name</td>
		<td>
					${applicationArrestLawbreaker.first_name}
				</td>
		</tr>
	<tr>
			<td>lawbreaker_passport</td>
		<td>
					${applicationArrestLawbreaker.lawbreaker_passport}
				</td>
		</tr>
	<tr>
			<td>lawbreaker_id_card</td>
		<td>
					${applicationArrestLawbreaker.lawbreaker_id_card}
				</td>
		</tr>
	<tr>
			<td>culprit_type</td>
		<td>
					${applicationArrestLawbreaker.culprit_type}
				</td>
		</tr>
	<tr>
			<td>lawbreaker_no</td>
		<td>
					${applicationArrestLawbreaker.lawbreaker_no}
				</td>
		</tr>
	<tr>
			<td>track_no</td>
		<td>
					${applicationArrestLawbreaker.track_no}
				</td>
		</tr>
	<tr>
		</tr>
</table>