// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.hsqldb.jdbcDriver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package com.ko.util;

import java.sql.SQLException;

/**
 * framework by boonchai ( neng )
 * @author <a href="mailto:mr.boonchai@gmail.com">Mr.Boonchai</a>
 */
public class DAOException extends SQLException
{
    private static final long serialVersionUID = 1432493376993389450L;

    private Throwable cause;

    /**
     * contructor
     */
    public DAOException()
    {
        super();
    }

    /**
     * contructor
     */
    public DAOException(String message)
    {
        super(message);
    }

    /**
     * contructor
     */
    public DAOException(Throwable cause)
    {
        this.cause = cause;
    }

    /**
     * contructor
     */
    public DAOException(String message, Throwable cause)
    {
        super(message);
        this.cause = cause;
    }
}
