








 

<%@ page language="java" errorPage="/error.jsp" pageEncoding="UTF-8" contentType="text/html;charset=utf-8" %>
<%@ include file="/Templates/taglibs.jsp"%>
<%@page import="com.ko.webapp.util.FormHandler,com.ko.webapp.util.PageUtil"%>
<%
	FormHandler formHandler = new FormHandler(request);
	PageUtil pageUtil = new PageUtil(request);
%>
<a href="<c:url value="/process2?action=ApplicationArrest&cmd=list"/>">Back</a>
<table><tr><td><font color="red"><%=formHandler.getFormMessage()%></font></td></tr></table>
<table border="1">
	<tr>
		<td>ID</td>
		<td>${applicationArrest.id}</td>
	</tr>
	<tr>
			<td>update_on</td>
		<td>
					<fmt:formatDate value="${applicationArrest.update_on}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>update_by</td>
		<td>
					${applicationArrest.update_by}
				</td>
		</tr>
	<tr>
			<td>create_on</td>
		<td>
					<fmt:formatDate value="${applicationArrest.create_on}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>create_by</td>
		<td>
					${applicationArrest.create_by}
				</td>
		</tr>
	<tr>
			<td>arrest_report_date</td>
		<td>
					<fmt:formatDate value="${applicationArrest.arrest_report_date}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>issentcourt</td>
		<td>
					${applicationArrest.issentcourt}
				</td>
		</tr>
	<tr>
			<td>accuser_poscode</td>
		<td>
					${applicationArrest.accuser_poscode}
				</td>
		</tr>
	<tr>
			<td>accuser_offcode</td>
		<td>
					${applicationArrest.accuser_offcode}
				</td>
		</tr>
	<tr>
			<td>accuser_idcardno</td>
		<td>
					${applicationArrest.accuser_idcardno}
				</td>
		</tr>
	<tr>
			<td>application_sincere_confirm_id</td>
		<td>
					${applicationArrest.application_sincere_confirm_id}
				</td>
		</tr>
	<tr>
			<td>application_search_warrant_id</td>
		<td>
					${applicationArrest.application_search_warrant_id}
				</td>
		</tr>
	<tr>
			<td>application_notice_arrest_id</td>
		<td>
					${applicationArrest.application_notice_arrest_id}
				</td>
		</tr>
	<tr>
			<td>police_station</td>
		<td>
					${applicationArrest.police_station}
				</td>
		</tr>
	<tr>
			<td>accuser_type</td>
		<td>
					${applicationArrest.accuser_type}
				</td>
		</tr>
	<tr>
			<td>product_group_id</td>
		<td>
					${applicationArrest.product_group_id}
				</td>
		</tr>
	<tr>
			<td>coordinate_y</td>
		<td>
					${applicationArrest.coordinate_y}
				</td>
		</tr>
	<tr>
			<td>coordinate_x</td>
		<td>
					${applicationArrest.coordinate_x}
				</td>
		</tr>
	<tr>
			<td>estimate_fine_date</td>
		<td>
					<fmt:formatDate value="${applicationArrest.estimate_fine_date}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>estimate_fine</td>
		<td>
					${applicationArrest.estimate_fine}
				</td>
		</tr>
	<tr>
			<td>del_flag</td>
		<td>
					${applicationArrest.del_flag}
				</td>
		</tr>
	<tr>
			<td>administration</td>
		<td>
					${applicationArrest.administration}
				</td>
		</tr>
	<tr>
			<td>lawbreak_type</td>
		<td>
					${applicationArrest.lawbreak_type}
				</td>
		</tr>
	<tr>
			<td>department_name</td>
		<td>
					${applicationArrest.department_name}
				</td>
		</tr>
	<tr>
			<td>finished_time</td>
		<td>
					<fmt:formatDate value="${applicationArrest.finished_time}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>testimony</td>
		<td>
					${applicationArrest.testimony}
				</td>
		</tr>
	<tr>
			<td>behaviour</td>
		<td>
					${applicationArrest.behaviour}
				</td>
		</tr>
	<tr>
			<td>director_position</td>
		<td>
					${applicationArrest.director_position}
				</td>
		</tr>
	<tr>
			<td>leader_position</td>
		<td>
					${applicationArrest.leader_position}
				</td>
		</tr>
	<tr>
			<td>order_by</td>
		<td>
					${applicationArrest.order_by}
				</td>
		</tr>
	<tr>
			<td>report_to</td>
		<td>
					${applicationArrest.report_to}
				</td>
		</tr>
	<tr>
			<td>duty</td>
		<td>
					${applicationArrest.duty}
				</td>
		</tr>
	<tr>
			<td>surety_name</td>
		<td>
					${applicationArrest.surety_name}
				</td>
		</tr>
	<tr>
			<td>business_name</td>
		<td>
					${applicationArrest.business_name}
				</td>
		</tr>
	<tr>
			<td>owner_name</td>
		<td>
					${applicationArrest.owner_name}
				</td>
		</tr>
	<tr>
			<td>guilty</td>
		<td>
					${applicationArrest.guilty}
				</td>
		</tr>
	<tr>
			<td>occurrence_date</td>
		<td>
					<fmt:formatDate value="${applicationArrest.occurrence_date}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>alleged_co</td>
		<td>
					${applicationArrest.alleged_co}
				</td>
		</tr>
	<tr>
			<td>scene_province</td>
		<td>
					${applicationArrest.scene_province}
				</td>
		</tr>
	<tr>
			<td>scene_district</td>
		<td>
					${applicationArrest.scene_district}
				</td>
		</tr>
	<tr>
			<td>scene_subdistrict</td>
		<td>
					${applicationArrest.scene_subdistrict}
				</td>
		</tr>
	<tr>
			<td>scene_road</td>
		<td>
					${applicationArrest.scene_road}
				</td>
		</tr>
	<tr>
			<td>scene_soi</td>
		<td>
					${applicationArrest.scene_soi}
				</td>
		</tr>
	<tr>
			<td>scene_moo</td>
		<td>
					${applicationArrest.scene_moo}
				</td>
		</tr>
	<tr>
			<td>scene_no</td>
		<td>
					${applicationArrest.scene_no}
				</td>
		</tr>
	<tr>
			<td>scene_name</td>
		<td>
					${applicationArrest.scene_name}
				</td>
		</tr>
	<tr>
			<td>have_culprit</td>
		<td>
					${applicationArrest.have_culprit}
				</td>
		</tr>
	<tr>
			<td>legislation_id</td>
		<td>
					${applicationArrest.legislation_id}
				</td>
		</tr>
	<tr>
			<td>offcode</td>
		<td>
					${applicationArrest.offcode}
				</td>
		</tr>
	<tr>
			<td>department_id</td>
		<td>
					${applicationArrest.department_id}
				</td>
		</tr>
	<tr>
			<td>application_date</td>
		<td>
					<fmt:formatDate value="${applicationArrest.application_date}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>track_no</td>
		<td>
					${applicationArrest.track_no}
				</td>
		</tr>
	<tr>
		</tr>
</table>