








 

<%@ page language="java" errorPage="/error.jsp" pageEncoding="UTF-8" contentType="text/html;charset=utf-8" %>
<%@ include file="/Templates/taglibs.jsp"%>
<%@page import="com.ko.webapp.util.FormHandler,com.ko.webapp.util.PageUtil"%>
<%
	FormHandler formHandler = new FormHandler(request);
	PageUtil pageUtil = new PageUtil(request);
%>
<a href="<c:url value="/process2?action=ApplicationNoticeArrest&cmd=list"/>">Back</a>
<table><tr><td><font color="red"><%=formHandler.getFormMessage()%></font></td></tr></table>
<table border="1">
	<tr>
		<td>ID</td>
		<td>${applicationNoticeArrest.id}</td>
	</tr>
	<tr>
			<td>isfingerapprove</td>
		<td>
					${applicationNoticeArrest.isfingerapprove}
				</td>
		</tr>
	<tr>
			<td>inform_type</td>
		<td>
					${applicationNoticeArrest.inform_type}
				</td>
		</tr>
	<tr>
			<td>del_flag</td>
		<td>
					${applicationNoticeArrest.del_flag}
				</td>
		</tr>
	<tr>
			<td>offcode</td>
		<td>
					${applicationNoticeArrest.offcode}
				</td>
		</tr>
	<tr>
			<td>update_on</td>
		<td>
					<fmt:formatDate value="${applicationNoticeArrest.update_on}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>update_by</td>
		<td>
					${applicationNoticeArrest.update_by}
				</td>
		</tr>
	<tr>
			<td>create_on</td>
		<td>
					<fmt:formatDate value="${applicationNoticeArrest.create_on}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>create_by</td>
		<td>
					${applicationNoticeArrest.create_by}
				</td>
		</tr>
	<tr>
			<td>isreward_pay</td>
		<td>
					${applicationNoticeArrest.isreward_pay}
				</td>
		</tr>
	<tr>
			<td>ismanage</td>
		<td>
					${applicationNoticeArrest.ismanage}
				</td>
		</tr>
	<tr>
			<td>notice_result</td>
		<td>
					${applicationNoticeArrest.notice_result}
				</td>
		</tr>
	<tr>
			<td>remarks</td>
		<td>
					${applicationNoticeArrest.remarks}
				</td>
		</tr>
	<tr>
			<td>next_step</td>
		<td>
					${applicationNoticeArrest.next_step}
				</td>
		</tr>
	<tr>
			<td>offcode_commander</td>
		<td>
					${applicationNoticeArrest.offcode_commander}
				</td>
		</tr>
	<tr>
			<td>poscode_commander</td>
		<td>
					${applicationNoticeArrest.poscode_commander}
				</td>
		</tr>
	<tr>
			<td>staff_id_commander</td>
		<td>
					${applicationNoticeArrest.staff_id_commander}
				</td>
		</tr>
	<tr>
			<td>staff_id_accept</td>
		<td>
					${applicationNoticeArrest.staff_id_accept}
				</td>
		</tr>
	<tr>
			<td>offcode_surety</td>
		<td>
					${applicationNoticeArrest.offcode_surety}
				</td>
		</tr>
	<tr>
			<td>poscode_surety</td>
		<td>
					${applicationNoticeArrest.poscode_surety}
				</td>
		</tr>
	<tr>
			<td>staff_id_surety</td>
		<td>
					${applicationNoticeArrest.staff_id_surety}
				</td>
		</tr>
	<tr>
			<td>offcode_receive</td>
		<td>
					${applicationNoticeArrest.offcode_receive}
				</td>
		</tr>
	<tr>
			<td>poscode_receive</td>
		<td>
					${applicationNoticeArrest.poscode_receive}
				</td>
		</tr>
	<tr>
			<td>staff_id_receive</td>
		<td>
					${applicationNoticeArrest.staff_id_receive}
				</td>
		</tr>
	<tr>
			<td>hiding_place</td>
		<td>
					${applicationNoticeArrest.hiding_place}
				</td>
		</tr>
	<tr>
			<td>vehicle_particular</td>
		<td>
					${applicationNoticeArrest.vehicle_particular}
				</td>
		</tr>
	<tr>
			<td>lawbreaker_province_code</td>
		<td>
					${applicationNoticeArrest.lawbreaker_province_code}
				</td>
		</tr>
	<tr>
			<td>lawbreaker_district_code</td>
		<td>
					${applicationNoticeArrest.lawbreaker_district_code}
				</td>
		</tr>
	<tr>
			<td>lawbreaker_subdistrict_code</td>
		<td>
					${applicationNoticeArrest.lawbreaker_subdistrict_code}
				</td>
		</tr>
	<tr>
			<td>lawbreaker_moo</td>
		<td>
					${applicationNoticeArrest.lawbreaker_moo}
				</td>
		</tr>
	<tr>
			<td>lawbreaker_road</td>
		<td>
					${applicationNoticeArrest.lawbreaker_road}
				</td>
		</tr>
	<tr>
			<td>lawbreaker_soi</td>
		<td>
					${applicationNoticeArrest.lawbreaker_soi}
				</td>
		</tr>
	<tr>
			<td>lawbreaker_address_name</td>
		<td>
					${applicationNoticeArrest.lawbreaker_address_name}
				</td>
		</tr>
	<tr>
			<td>lawbreaker_address</td>
		<td>
					${applicationNoticeArrest.lawbreaker_address}
				</td>
		</tr>
	<tr>
			<td>secret_level</td>
		<td>
					${applicationNoticeArrest.secret_level}
				</td>
		</tr>
	<tr>
			<td>arrest_desc</td>
		<td>
					${applicationNoticeArrest.arrest_desc}
				</td>
		</tr>
	<tr>
			<td>inform_province_code</td>
		<td>
					${applicationNoticeArrest.inform_province_code}
				</td>
		</tr>
	<tr>
			<td>inform_district_code</td>
		<td>
					${applicationNoticeArrest.inform_district_code}
				</td>
		</tr>
	<tr>
			<td>inform_subdistrict_code</td>
		<td>
					${applicationNoticeArrest.inform_subdistrict_code}
				</td>
		</tr>
	<tr>
			<td>inform_moo</td>
		<td>
					${applicationNoticeArrest.inform_moo}
				</td>
		</tr>
	<tr>
			<td>inform_road</td>
		<td>
					${applicationNoticeArrest.inform_road}
				</td>
		</tr>
	<tr>
			<td>inform_soi</td>
		<td>
					${applicationNoticeArrest.inform_soi}
				</td>
		</tr>
	<tr>
			<td>inform_address_name</td>
		<td>
					${applicationNoticeArrest.inform_address_name}
				</td>
		</tr>
	<tr>
			<td>inform_address</td>
		<td>
					${applicationNoticeArrest.inform_address}
				</td>
		</tr>
	<tr>
			<td>inform_age</td>
		<td>
					${applicationNoticeArrest.inform_age}
				</td>
		</tr>
	<tr>
			<td>inform_name</td>
		<td>
					${applicationNoticeArrest.inform_name}
				</td>
		</tr>
	<tr>
			<td>lawbreaker_no</td>
		<td>
					${applicationNoticeArrest.lawbreaker_no}
				</td>
		</tr>
	<tr>
			<td>receive_date</td>
		<td>
					<fmt:formatDate value="${applicationNoticeArrest.receive_date}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>duty_code</td>
		<td>
					${applicationNoticeArrest.duty_code}
				</td>
		</tr>
	<tr>
			<td>legislation_id</td>
		<td>
					${applicationNoticeArrest.legislation_id}
				</td>
		</tr>
	<tr>
			<td>offname</td>
		<td>
					${applicationNoticeArrest.offname}
				</td>
		</tr>
	<tr>
			<td>notice_date</td>
		<td>
					<fmt:formatDate value="${applicationNoticeArrest.notice_date}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>notice_no</td>
		<td>
					${applicationNoticeArrest.notice_no}
				</td>
		</tr>
	<tr>
		</tr>
</table>