








 

<%@ page language="java" errorPage="/error.jsp" pageEncoding="UTF-8" contentType="text/html;charset=utf-8" %>
<%@ include file="/Templates/taglibs.jsp"%>
<%@page import="com.ko.webapp.util.FormHandler,com.ko.webapp.util.PageUtil"%>
<%
	FormHandler formHandler = new FormHandler(request);
	PageUtil pageUtil = new PageUtil(request);
%>
<a href="<c:url value="/process2?action=ApplicationSearchWarrant&cmd=list"/>">Back</a>
<table><tr><td><font color="red"><%=formHandler.getFormMessage()%></font></td></tr></table>
<table border="1">
	<tr>
		<td>ID</td>
		<td>${applicationSearchWarrant.id}</td>
	</tr>
	<tr>
			<td>application_notice_arrest_id</td>
		<td>
					${applicationSearchWarrant.application_notice_arrest_id}
				</td>
		</tr>
	<tr>
			<td>result_qty_date</td>
		<td>
					${applicationSearchWarrant.result_qty_date}
				</td>
		</tr>
	<tr>
			<td>court_order_familiar</td>
		<td>
					${applicationSearchWarrant.court_order_familiar}
				</td>
		</tr>
	<tr>
			<td>offcode_assign</td>
		<td>
					${applicationSearchWarrant.offcode_assign}
				</td>
		</tr>
	<tr>
			<td>poscode_assign</td>
		<td>
					${applicationSearchWarrant.poscode_assign}
				</td>
		</tr>
	<tr>
			<td>staff_id_assign</td>
		<td>
					${applicationSearchWarrant.staff_id_assign}
				</td>
		</tr>
	<tr>
			<td>offcode_req_for</td>
		<td>
					${applicationSearchWarrant.offcode_req_for}
				</td>
		</tr>
	<tr>
			<td>poscode_req_for</td>
		<td>
					${applicationSearchWarrant.poscode_req_for}
				</td>
		</tr>
	<tr>
			<td>staff_id_req_for</td>
		<td>
					${applicationSearchWarrant.staff_id_req_for}
				</td>
		</tr>
	<tr>
			<td>tel_request</td>
		<td>
					${applicationSearchWarrant.tel_request}
				</td>
		</tr>
	<tr>
			<td>career_request</td>
		<td>
					${applicationSearchWarrant.career_request}
				</td>
		</tr>
	<tr>
			<td>track_no</td>
		<td>
					${applicationSearchWarrant.track_no}
				</td>
		</tr>
	<tr>
			<td>office_address</td>
		<td>
					${applicationSearchWarrant.office_address}
				</td>
		</tr>
	<tr>
			<td>update_on</td>
		<td>
					<fmt:formatDate value="${applicationSearchWarrant.update_on}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>update_by</td>
		<td>
					${applicationSearchWarrant.update_by}
				</td>
		</tr>
	<tr>
			<td>create_on</td>
		<td>
					<fmt:formatDate value="${applicationSearchWarrant.create_on}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>create_by</td>
		<td>
					${applicationSearchWarrant.create_by}
				</td>
		</tr>
	<tr>
			<td>search_result</td>
		<td>
					${applicationSearchWarrant.search_result}
				</td>
		</tr>
	<tr>
			<td>send_to_desc</td>
		<td>
					${applicationSearchWarrant.send_to_desc}
				</td>
		</tr>
	<tr>
			<td>send_desc</td>
		<td>
					${applicationSearchWarrant.send_desc}
				</td>
		</tr>
	<tr>
			<td>court_id_arrest</td>
		<td>
					${applicationSearchWarrant.court_id_arrest}
				</td>
		</tr>
	<tr>
			<td>arrest_date</td>
		<td>
					<fmt:formatDate value="${applicationSearchWarrant.arrest_date}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>arrest_no</td>
		<td>
					${applicationSearchWarrant.arrest_no}
				</td>
		</tr>
	<tr>
			<td>search_check2_2</td>
		<td>
					${applicationSearchWarrant.search_check2_2}
				</td>
		</tr>
	<tr>
			<td>search_check2_1</td>
		<td>
					${applicationSearchWarrant.search_check2_1}
				</td>
		</tr>
	<tr>
			<td>search_check2_desc</td>
		<td>
					${applicationSearchWarrant.search_check2_desc}
				</td>
		</tr>
	<tr>
			<td>search_check2</td>
		<td>
					${applicationSearchWarrant.search_check2}
				</td>
		</tr>
	<tr>
			<td>search_check1_3</td>
		<td>
					${applicationSearchWarrant.search_check1_3}
				</td>
		</tr>
	<tr>
			<td>search_check1_2</td>
		<td>
					${applicationSearchWarrant.search_check1_2}
				</td>
		</tr>
	<tr>
			<td>search_check1_1</td>
		<td>
					${applicationSearchWarrant.search_check1_1}
				</td>
		</tr>
	<tr>
			<td>search_check1_desc</td>
		<td>
					${applicationSearchWarrant.search_check1_desc}
				</td>
		</tr>
	<tr>
			<td>search_check1</td>
		<td>
					${applicationSearchWarrant.search_check1}
				</td>
		</tr>
	<tr>
			<td>jedge_name</td>
		<td>
					${applicationSearchWarrant.jedge_name}
				</td>
		</tr>
	<tr>
			<td>warrant_date</td>
		<td>
					<fmt:formatDate value="${applicationSearchWarrant.warrant_date}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>warrant_no</td>
		<td>
					${applicationSearchWarrant.warrant_no}
				</td>
		</tr>
	<tr>
			<td>remarks_nonapprove</td>
		<td>
					${applicationSearchWarrant.remarks_nonapprove}
				</td>
		</tr>
	<tr>
			<td>isapprove</td>
		<td>
					${applicationSearchWarrant.isapprove}
				</td>
		</tr>
	<tr>
			<td>iscopy</td>
		<td>
					${applicationSearchWarrant.iscopy}
				</td>
		</tr>
	<tr>
			<td>isallow</td>
		<td>
					${applicationSearchWarrant.isallow}
				</td>
		</tr>
	<tr>
			<td>court_order</td>
		<td>
					${applicationSearchWarrant.court_order}
				</td>
		</tr>
	<tr>
			<td>witness_qty</td>
		<td>
					${applicationSearchWarrant.witness_qty}
				</td>
		</tr>
	<tr>
			<td>consider_date</td>
		<td>
					<fmt:formatDate value="${applicationSearchWarrant.consider_date}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>cause_familiar</td>
		<td>
					${applicationSearchWarrant.cause_familiar}
				</td>
		</tr>
	<tr>
			<td>court_id_familiar</td>
		<td>
					${applicationSearchWarrant.court_id_familiar}
				</td>
		</tr>
	<tr>
			<td>request_familiar</td>
		<td>
					${applicationSearchWarrant.request_familiar}
				</td>
		</tr>
	<tr>
			<td>province_code</td>
		<td>
					${applicationSearchWarrant.province_code}
				</td>
		</tr>
	<tr>
			<td>district_code</td>
		<td>
					${applicationSearchWarrant.district_code}
				</td>
		</tr>
	<tr>
			<td>subdistrict_code</td>
		<td>
					${applicationSearchWarrant.subdistrict_code}
				</td>
		</tr>
	<tr>
			<td>moo</td>
		<td>
					${applicationSearchWarrant.moo}
				</td>
		</tr>
	<tr>
			<td>soi</td>
		<td>
					${applicationSearchWarrant.soi}
				</td>
		</tr>
	<tr>
			<td>address_name</td>
		<td>
					${applicationSearchWarrant.address_name}
				</td>
		</tr>
	<tr>
			<td>address_no</td>
		<td>
					${applicationSearchWarrant.address_no}
				</td>
		</tr>
	<tr>
			<td>road</td>
		<td>
					${applicationSearchWarrant.road}
				</td>
		</tr>
	<tr>
			<td>owner_position</td>
		<td>
					${applicationSearchWarrant.owner_position}
				</td>
		</tr>
	<tr>
			<td>owner_career</td>
		<td>
					${applicationSearchWarrant.owner_career}
				</td>
		</tr>
	<tr>
			<td>owner_age</td>
		<td>
					${applicationSearchWarrant.owner_age}
				</td>
		</tr>
	<tr>
			<td>owner_name</td>
		<td>
					${applicationSearchWarrant.owner_name}
				</td>
		</tr>
	<tr>
			<td>req_check5</td>
		<td>
					${applicationSearchWarrant.req_check5}
				</td>
		</tr>
	<tr>
			<td>req_check4</td>
		<td>
					${applicationSearchWarrant.req_check4}
				</td>
		</tr>
	<tr>
			<td>req_check3</td>
		<td>
					${applicationSearchWarrant.req_check3}
				</td>
		</tr>
	<tr>
			<td>req_check2</td>
		<td>
					${applicationSearchWarrant.req_check2}
				</td>
		</tr>
	<tr>
			<td>req_check1</td>
		<td>
					${applicationSearchWarrant.req_check1}
				</td>
		</tr>
	<tr>
			<td>search_cause</td>
		<td>
					${applicationSearchWarrant.search_cause}
				</td>
		</tr>
	<tr>
			<td>chk_continue</td>
		<td>
					${applicationSearchWarrant.chk_continue}
				</td>
		</tr>
	<tr>
			<td>search_dateto</td>
		<td>
					<fmt:formatDate value="${applicationSearchWarrant.search_dateto}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>search_datefrom</td>
		<td>
					<fmt:formatDate value="${applicationSearchWarrant.search_datefrom}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>court_id</td>
		<td>
					${applicationSearchWarrant.court_id}
				</td>
		</tr>
	<tr>
			<td>age_request</td>
		<td>
					${applicationSearchWarrant.age_request}
				</td>
		</tr>
	<tr>
			<td>offcode_request</td>
		<td>
					${applicationSearchWarrant.offcode_request}
				</td>
		</tr>
	<tr>
			<td>poscode_request</td>
		<td>
					${applicationSearchWarrant.poscode_request}
				</td>
		</tr>
	<tr>
			<td>staff_id_request</td>
		<td>
					${applicationSearchWarrant.staff_id_request}
				</td>
		</tr>
	<tr>
			<td>request_date</td>
		<td>
					<fmt:formatDate value="${applicationSearchWarrant.request_date}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>request_no</td>
		<td>
					${applicationSearchWarrant.request_no}
				</td>
		</tr>
	<tr>
		</tr>
</table>