








 

<%@ page language="java" errorPage="/error.jsp" pageEncoding="UTF-8" contentType="text/html;charset=utf-8" %>
<%@ include file="/Templates/taglibs.jsp"%>
<%@page import="com.ko.webapp.util.FormHandler,com.ko.webapp.util.PageUtil"%>
<%
	FormHandler formHandler = new FormHandler(request);
	PageUtil pageUtil = new PageUtil(request);
%>
<a href="<c:url value="/process2?action=Lawbreaker&cmd=list"/>">Back</a>
<table><tr><td><font color="red"><%=formHandler.getFormMessage()%></font></td></tr></table>
<table border="1">
	<tr>
		<td>ID</td>
		<td>${lawbreaker.id}</td>
	</tr>
	<tr>
			<td>description</td>
		<td>
					${lawbreaker.description}
				</td>
		</tr>
	<tr>
			<td>mobile</td>
		<td>
					${lawbreaker.mobile}
				</td>
		</tr>
	<tr>
			<td>license_no</td>
		<td>
					${lawbreaker.license_no}
				</td>
		</tr>
	<tr>
			<td>license_date_to</td>
		<td>
					<fmt:formatDate value="${lawbreaker.license_date_to}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>license_date_from</td>
		<td>
					<fmt:formatDate value="${lawbreaker.license_date_from}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>photo_desc</td>
		<td>
					${lawbreaker.photo_desc}
				</td>
		</tr>
	<tr>
			<td>link_photo</td>
		<td>
					<img src="<c:url value='/process?action=GetImage'/>&table=LAWBREAKER&id=${lawbreaker.id}" widht=100 height=100>
				</td>
		</tr>
	<tr>
			<td>company_name</td>
		<td>
					${lawbreaker.company_name}
				</td>
		</tr>
	<tr>
			<td>title_code_company</td>
		<td>
					${lawbreaker.title_code_company}
				</td>
		</tr>
	<tr>
			<td>date_out</td>
		<td>
					<fmt:formatDate value="${lawbreaker.date_out}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>date_in</td>
		<td>
					<fmt:formatDate value="${lawbreaker.date_in}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>visa_type</td>
		<td>
					${lawbreaker.visa_type}
				</td>
		</tr>
	<tr>
			<td>passport_country</td>
		<td>
					${lawbreaker.passport_country}
				</td>
		</tr>
	<tr>
			<td>country_code</td>
		<td>
					${lawbreaker.country_code}
				</td>
		</tr>
	<tr>
			<td>del_flag</td>
		<td>
					${lawbreaker.del_flag}
				</td>
		</tr>
	<tr>
			<td>coordinate_y</td>
		<td>
					${lawbreaker.coordinate_y}
				</td>
		</tr>
	<tr>
			<td>coordinate_x</td>
		<td>
					${lawbreaker.coordinate_x}
				</td>
		</tr>
	<tr>
			<td>address_name</td>
		<td>
					${lawbreaker.address_name}
				</td>
		</tr>
	<tr>
			<td>modify_date</td>
		<td>
					<fmt:formatDate value="${lawbreaker.modify_date}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>modify_id</td>
		<td>
					${lawbreaker.modify_id}
				</td>
		</tr>
	<tr>
			<td>create_date</td>
		<td>
					<fmt:formatDate value="${lawbreaker.create_date}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>create_id</td>
		<td>
					${lawbreaker.create_id}
				</td>
		</tr>
	<tr>
			<td>remarks</td>
		<td>
					${lawbreaker.remarks}
				</td>
		</tr>
	<tr>
			<td>corporation_code</td>
		<td>
					${lawbreaker.corporation_code}
				</td>
		</tr>
	<tr>
			<td>excise_reg_no</td>
		<td>
					${lawbreaker.excise_reg_no}
				</td>
		</tr>
	<tr>
			<td>tax_id_no</td>
		<td>
					${lawbreaker.tax_id_no}
				</td>
		</tr>
	<tr>
			<td>email</td>
		<td>
					${lawbreaker.email}
				</td>
		</tr>
	<tr>
			<td>tel</td>
		<td>
					${lawbreaker.tel}
				</td>
		</tr>
	<tr>
			<td>post_code</td>
		<td>
					${lawbreaker.post_code}
				</td>
		</tr>
	<tr>
			<td>province_code</td>
		<td>
					${lawbreaker.province_code}
				</td>
		</tr>
	<tr>
			<td>district_code</td>
		<td>
					${lawbreaker.district_code}
				</td>
		</tr>
	<tr>
			<td>subdistrict_code</td>
		<td>
					${lawbreaker.subdistrict_code}
				</td>
		</tr>
	<tr>
			<td>road</td>
		<td>
					${lawbreaker.road}
				</td>
		</tr>
	<tr>
			<td>soi</td>
		<td>
					${lawbreaker.soi}
				</td>
		</tr>
	<tr>
			<td>moo</td>
		<td>
					${lawbreaker.moo}
				</td>
		</tr>
	<tr>
			<td>address_no</td>
		<td>
					${lawbreaker.address_no}
				</td>
		</tr>
	<tr>
			<td>career</td>
		<td>
					${lawbreaker.career}
				</td>
		</tr>
	<tr>
			<td>nation_id</td>
		<td>
					${lawbreaker.nation_id}
				</td>
		</tr>
	<tr>
			<td>race_id</td>
		<td>
					${lawbreaker.race_id}
				</td>
		</tr>
	<tr>
			<td>religion_id</td>
		<td>
					${lawbreaker.religion_id}
				</td>
		</tr>
	<tr>
			<td>blood_type</td>
		<td>
					${lawbreaker.blood_type}
				</td>
		</tr>
	<tr>
			<td>marital_status</td>
		<td>
					${lawbreaker.marital_status}
				</td>
		</tr>
	<tr>
			<td>sex</td>
		<td>
					${lawbreaker.sex}
				</td>
		</tr>
	<tr>
			<td>birth_date</td>
		<td>
					<fmt:formatDate value="${lawbreaker.birth_date}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>height</td>
		<td>
					${lawbreaker.height}
				</td>
		</tr>
	<tr>
			<td>other_name</td>
		<td>
					${lawbreaker.other_name}
				</td>
		</tr>
	<tr>
			<td>last_name</td>
		<td>
					${lawbreaker.last_name}
				</td>
		</tr>
	<tr>
			<td>middle_name</td>
		<td>
					${lawbreaker.middle_name}
				</td>
		</tr>
	<tr>
			<td>first_name</td>
		<td>
					${lawbreaker.first_name}
				</td>
		</tr>
	<tr>
			<td>title_code</td>
		<td>
					${lawbreaker.title_code}
				</td>
		</tr>
	<tr>
			<td>lawbreaker_passport</td>
		<td>
					${lawbreaker.lawbreaker_passport}
				</td>
		</tr>
	<tr>
			<td>lawbreaker_id_card</td>
		<td>
					${lawbreaker.lawbreaker_id_card}
				</td>
		</tr>
	<tr>
			<td>lawbreaker_type</td>
		<td>
					${lawbreaker.lawbreaker_type}
				</td>
		</tr>
	<tr>
			<td>lawbreaker_no</td>
		<td>
					${lawbreaker.lawbreaker_no}
				</td>
		</tr>
	<tr>
		</tr>
</table>