








 

<%@ page language="java" errorPage="/error.jsp" pageEncoding="UTF-8" contentType="text/html;charset=utf-8" %>
<%@ include file="/Templates/taglibs.jsp"%>
<%@page import="com.ko.webapp.util.FormHandler,com.ko.webapp.util.PageUtil"%>
<%
	FormHandler formHandler = new FormHandler(request);
	PageUtil pageUtil = new PageUtil(request);
%>
<a href="<c:url value="/process2?action=Suspect&cmd=list"/>">Back</a>
<table><tr><td><font color="red"><%=formHandler.getFormMessage()%></font></td></tr></table>
<table border="1">
	<tr>
		<td>ID</td>
		<td>${suspect.id}</td>
	</tr>
	<tr>
			<td>passport_country</td>
		<td>
					${suspect.passport_country}
				</td>
		</tr>
	<tr>
			<td>del_flag</td>
		<td>
					${suspect.del_flag}
				</td>
		</tr>
	<tr>
			<td>offcode</td>
		<td>
					${suspect.offcode}
				</td>
		</tr>
	<tr>
			<td>mime_type</td>
		<td>
					${suspect.mime_type}
				</td>
		</tr>
	<tr>
			<td>update_date</td>
		<td>
					<fmt:formatDate value="${suspect.update_date}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>update_id</td>
		<td>
					${suspect.update_id}
				</td>
		</tr>
	<tr>
			<td>link_photo</td>
		<td>
					<img src="<c:url value='/process?action=GetImage'/>&table=SUSPECT&id=${suspect.id}" widht=100 height=100>
				</td>
		</tr>
	<tr>
			<td>license_date_to</td>
		<td>
					<fmt:formatDate value="${suspect.license_date_to}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>license_date_from</td>
		<td>
					<fmt:formatDate value="${suspect.license_date_from}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>company_name</td>
		<td>
					${suspect.company_name}
				</td>
		</tr>
	<tr>
			<td>title_code_company</td>
		<td>
					${suspect.title_code_company}
				</td>
		</tr>
	<tr>
			<td>photo_desc</td>
		<td>
					${suspect.photo_desc}
				</td>
		</tr>
	<tr>
			<td>mobile</td>
		<td>
					${suspect.mobile}
				</td>
		</tr>
	<tr>
			<td>country_code</td>
		<td>
					${suspect.country_code}
				</td>
		</tr>
	<tr>
			<td>date_out</td>
		<td>
					<fmt:formatDate value="${suspect.date_out}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>date_in</td>
		<td>
					<fmt:formatDate value="${suspect.date_in}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>visa_type</td>
		<td>
					${suspect.visa_type}
				</td>
		</tr>
	<tr>
			<td>create_date</td>
		<td>
					<fmt:formatDate value="${suspect.create_date}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>create_id</td>
		<td>
					${suspect.create_id}
				</td>
		</tr>
	<tr>
			<td>description</td>
		<td>
					${suspect.description}
				</td>
		</tr>
	<tr>
			<td>license_no</td>
		<td>
					${suspect.license_no}
				</td>
		</tr>
	<tr>
			<td>corporation_code</td>
		<td>
					${suspect.corporation_code}
				</td>
		</tr>
	<tr>
			<td>excise_reg_no</td>
		<td>
					${suspect.excise_reg_no}
				</td>
		</tr>
	<tr>
			<td>tax_id_no</td>
		<td>
					${suspect.tax_id_no}
				</td>
		</tr>
	<tr>
			<td>email</td>
		<td>
					${suspect.email}
				</td>
		</tr>
	<tr>
			<td>tel</td>
		<td>
					${suspect.tel}
				</td>
		</tr>
	<tr>
			<td>coordinate_y</td>
		<td>
					${suspect.coordinate_y}
				</td>
		</tr>
	<tr>
			<td>coordinate_x</td>
		<td>
					${suspect.coordinate_x}
				</td>
		</tr>
	<tr>
			<td>post_code</td>
		<td>
					${suspect.post_code}
				</td>
		</tr>
	<tr>
			<td>province_code</td>
		<td>
					${suspect.province_code}
				</td>
		</tr>
	<tr>
			<td>district_code</td>
		<td>
					${suspect.district_code}
				</td>
		</tr>
	<tr>
			<td>subdistrict_code</td>
		<td>
					${suspect.subdistrict_code}
				</td>
		</tr>
	<tr>
			<td>road</td>
		<td>
					${suspect.road}
				</td>
		</tr>
	<tr>
			<td>soi</td>
		<td>
					${suspect.soi}
				</td>
		</tr>
	<tr>
			<td>moo</td>
		<td>
					${suspect.moo}
				</td>
		</tr>
	<tr>
			<td>address_no</td>
		<td>
					${suspect.address_no}
				</td>
		</tr>
	<tr>
			<td>address_name</td>
		<td>
					${suspect.address_name}
				</td>
		</tr>
	<tr>
			<td>career</td>
		<td>
					${suspect.career}
				</td>
		</tr>
	<tr>
			<td>nation_id</td>
		<td>
					${suspect.nation_id}
				</td>
		</tr>
	<tr>
			<td>race_id</td>
		<td>
					${suspect.race_id}
				</td>
		</tr>
	<tr>
			<td>religion_id</td>
		<td>
					${suspect.religion_id}
				</td>
		</tr>
	<tr>
			<td>blood_type</td>
		<td>
					${suspect.blood_type}
				</td>
		</tr>
	<tr>
			<td>marital_status</td>
		<td>
					${suspect.marital_status}
				</td>
		</tr>
	<tr>
			<td>sex</td>
		<td>
					${suspect.sex}
				</td>
		</tr>
	<tr>
			<td>birth_date</td>
		<td>
					<fmt:formatDate value="${suspect.birth_date}" pattern="dd/MM/yyyy"/>
				</td>
		</tr>
	<tr>
			<td>height</td>
		<td>
					${suspect.height}
				</td>
		</tr>
	<tr>
			<td>other_name</td>
		<td>
					${suspect.other_name}
				</td>
		</tr>
	<tr>
			<td>last_name</td>
		<td>
					${suspect.last_name}
				</td>
		</tr>
	<tr>
			<td>middle_name</td>
		<td>
					${suspect.middle_name}
				</td>
		</tr>
	<tr>
			<td>first_name</td>
		<td>
					${suspect.first_name}
				</td>
		</tr>
	<tr>
			<td>title_code</td>
		<td>
					${suspect.title_code}
				</td>
		</tr>
	<tr>
			<td>suspect_passport</td>
		<td>
					${suspect.suspect_passport}
				</td>
		</tr>
	<tr>
			<td>suspect_id_card</td>
		<td>
					${suspect.suspect_id_card}
				</td>
		</tr>
	<tr>
			<td>suspect_type</td>
		<td>
					${suspect.suspect_type}
				</td>
		</tr>
	<tr>
			<td>suspect_no</td>
		<td>
					${suspect.suspect_no}
				</td>
		</tr>
	<tr>
		</tr>
</table>