'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5485
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class ucRewardRequestTax

    '''<summary>
    '''lblApplicationRewardRequestID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblApplicationRewardRequestID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTrackNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTrackNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReportName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReportName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProductGroupName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProductGroupName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkInform control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkInform As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkCountInform control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCountInform As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''gvExhibit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvExhibit As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtAbnormaly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAbnormaly As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvArrestHelper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvArrestHelper As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnAddHelperSaffList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddHelperSaffList As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''frmPopHelperList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmPopHelperList As Global.XCS_Admin.frmPopArrestTeam

    '''<summary>
    '''btnDeleteHelperStaffList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteHelperStaffList As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblControlStaffName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblControlStaffName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblControlStaffID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblControlStaffID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblControlPoscode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblControlPoscode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblControlOffcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblControlOffcode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSearchControlStaff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchControlStaff As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''frmSearchControlStaff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmSearchControlStaff As Global.XCS_Admin.frmSearchStaff

    '''<summary>
    '''lblControlPosname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblControlPosname As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCommentControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCommentControl As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCommentInitial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCommentInitial As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblInitialStaffName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInitialStaffName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInitialStaffID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInitialStaffID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInitialStaffPoscode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInitialStaffPoscode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInitialStaffOffcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInitialStaffOffcode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSearchInitialStaff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchInitialStaff As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''frmSearchInitialStaff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmSearchInitialStaff As Global.XCS_Admin.frmSearchStaff

    '''<summary>
    '''lblInitialStaffPosname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInitialStaffPosname As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCommentCommander control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCommentCommander As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCommanderStaffName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCommanderStaffName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCommanderStaffID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCommanderStaffID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCommanderPoscode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCommanderPoscode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCommanderOffcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCommanderOffcode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSearchCommanderStaff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchCommanderStaff As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''frmSearchCommanderStaff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmSearchCommanderStaff As Global.XCS_Admin.frmSearchStaff

    '''<summary>
    '''lblCommanderPosname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCommanderPosname As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCommand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCommand As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblConfirmStaffName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConfirmStaffName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblConfirmStaffID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConfirmStaffID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblConfirmStaffPoscode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConfirmStaffPoscode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblConfirmStaffOffcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConfirmStaffOffcode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSearchConfirmStaff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchConfirmStaff As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''frmSearchConfirmStaff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmSearchConfirmStaff As Global.XCS_Admin.frmSearchStaff

    '''<summary>
    '''lblConfirmStaffPosname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConfirmStaffPosname As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAccuserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccuserName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAccuserPosname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccuserPosname As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOccurrenceDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOccurrenceDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCaseTotalFine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCaseTotalFine As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''alCaseTotalFine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents alCaseTotalFine As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBribeP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBribeP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBribeMoney control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBribeMoney As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''alBirbeText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents alBirbeText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRewardP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRewardP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRewardMoney control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRewardMoney As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''alRewardText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents alRewardText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAskLean control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAskLean As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDepartmentSend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDepartmentSend As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAskStaffName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAskStaffName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAskStaffID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAskStaffID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAskPoscode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAskPoscode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAskOffcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAskOffcode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSearchAskStaff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchAskStaff As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''frmSearchAskStaff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmSearchAskStaff As Global.XCS_Admin.frmSearchStaff

    '''<summary>
    '''lblAskPosname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAskPosname As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtApproveLean control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtApproveLean As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblApproveStaffName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblApproveStaffName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblApproveStaffID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblApproveStaffID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblApproveStaffPoscode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblApproveStaffPoscode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblApproveStaffOffcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblApproveStaffOffcode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSearchApproveStaff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchApproveStaff As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''frmSearchApproveStafff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmSearchApproveStafff As Global.XCS_Admin.frmSearchStaff

    '''<summary>
    '''lblApproveStaffPosname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblApproveStaffPosname As Global.System.Web.UI.WebControls.Label
End Class
