'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5485
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class ucRewardRequestTobacco

    '''<summary>
    '''lblApplicationRewardRequestID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblApplicationRewardRequestID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSueStaffName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSueStaffName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSueStaffPosname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSueStaffPosname As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCaseTotalFine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCaseTotalFine As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''alCaseTotalFine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents alCaseTotalFine As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOccurrenceDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOccurrenceDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRewardP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRewardP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRewardMoney control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRewardMoney As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''alRewardText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents alRewardText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAccuserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccuserName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAccuserStaffID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccuserStaffID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAccuserPoscode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccuserPoscode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAccuserOffcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccuserOffcode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSearchAccuserStaff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchAccuserStaff As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''frmSearchAccuserStaff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmSearchAccuserStaff As Global.XCS_Admin.frmSearchStaff

    '''<summary>
    '''lblAccuserPosname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccuserPosname As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtLawerOpinion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLawerOpinion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDirectorPosition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDirectorPosition As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDirectorOpinion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDirectorOpinion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCommand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCommand As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtArrestOpinion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtArrestOpinion As Global.System.Web.UI.WebControls.TextBox
End Class
